# Generated by Django 5.0.1 on 2026-06-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etainabl_api_url",
                    models.URLField(
                        default="https://api.etainabl.com/2.0",
                        help_text="Base URL for Etainabl API",
                    ),
                ),
                (
                    "page_size",
                    models.IntegerField(
                        default=50,
                        help_text="Number of records to fetch per API request",
                    ),
                ),
                (
                    "api_timeout",
                    models.IntegerField(
                        default=30, help_text="API request timeout in seconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "App Settings",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier from Etainabl API (asset ID)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Site name from Etainabl API", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Site description", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["external_id"], name="sitesync_si_externa_93caef_idx"
                    ),
                    models.Index(fields=["name"], name="sitesync_si_name_b45c71_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier from Etainabl API (account ID)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Supply name from Etainabl API", max_length=500
                    ),
                ),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("gas", "Gas"),
                            ("water", "Water"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of utility supply",
                        max_length=20,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Device ID (meter/sensor identifier)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Associated site",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies",
                        to="sitesync.site",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["external_id"], name="sitesync_su_externa_491fde_idx"
                    ),
                    models.Index(
                        fields=["site", "name"], name="sitesync_su_site_id_5d7b28_idx"
                    ),
                ],
            },
        ),
    ]
