# Generated by Django 5.0.1 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="parent_account_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Parent fiscal meter account ID from Etainabl parentAccountId",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="supply",
            index=models.Index(
                fields=["site", "parent_account_id"],
                name="sitesync_su_site_id_451ab0_idx",
            ),
        ),
    ]
