# Generated by Django 6.0.6 on 2026-07-01 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesync", "0002_supply_parent_account_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HalfHourlyConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canonical_month_key", models.CharField(db_index=True, max_length=7)),
                ("source_period_start", models.DateTimeField()),
                ("source_period_end", models.DateTimeField()),
                ("consumption", models.DecimalField(decimal_places=6, max_digits=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-source_period_start"],
            },
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("selected_supply_ids", models.JSONField(default=list)),
                ("reporting_month", models.CharField(db_index=True, max_length=7)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("partial_failure", "Partial Failure"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("affected_supply_count", models.IntegerField(default=0)),
                ("records_imported", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("retry_count", models.IntegerField(default=0)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("outcome_details", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canonical_month_key", models.CharField(db_index=True, max_length=7)),
                ("source_period_start", models.DateTimeField()),
                ("source_period_end", models.DateTimeField()),
                ("cost", models.DecimalField(decimal_places=6, max_digits=16)),
                ("invoice_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-source_period_start"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canonical_month_key", models.CharField(db_index=True, max_length=7)),
                ("source_period_start", models.DateTimeField()),
                ("source_period_end", models.DateTimeField()),
                ("consumption", models.DecimalField(decimal_places=6, max_digits=16)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-source_period_start"],
            },
        ),
        migrations.RenameIndex(
            model_name="supply",
            new_name="sitesync_su_site_id_107d70_idx",
            old_name="sitesync_su_site_id_451ab0_idx",
        ),
        migrations.AddField(
            model_name="halfhourlyconsumption",
            name="supply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="halfhourly_consumption",
                to="sitesync.supply",
            ),
        ),
        migrations.AddIndex(
            model_name="importrun",
            index=models.Index(
                fields=["reporting_month"], name="sitesync_im_reporti_01c206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrun",
            index=models.Index(fields=["status"], name="sitesync_im_status_cb7acb_idx"),
        ),
        migrations.AddIndex(
            model_name="importrun",
            index=models.Index(
                fields=["created_at"], name="sitesync_im_created_91160a_idx"
            ),
        ),
        migrations.AddField(
            model_name="halfhourlyconsumption",
            name="import_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="halfhourly_records",
                to="sitesync.importrun",
            ),
        ),
        migrations.AddField(
            model_name="invoicecost",
            name="import_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_records",
                to="sitesync.importrun",
            ),
        ),
        migrations.AddField(
            model_name="invoicecost",
            name="supply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_costs",
                to="sitesync.supply",
            ),
        ),
        migrations.AddField(
            model_name="monthlyconsumption",
            name="import_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_records",
                to="sitesync.importrun",
            ),
        ),
        migrations.AddField(
            model_name="monthlyconsumption",
            name="supply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_consumption",
                to="sitesync.supply",
            ),
        ),
        migrations.AddIndex(
            model_name="halfhourlyconsumption",
            index=models.Index(
                fields=["canonical_month_key"], name="sitesync_ha_canonic_5d4314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="halfhourlyconsumption",
            index=models.Index(
                fields=["supply", "canonical_month_key"],
                name="sitesync_ha_supply__2f7172_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="halfhourlyconsumption",
            index=models.Index(
                fields=["import_run"], name="sitesync_ha_import__1d0818_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="halfhourlyconsumption",
            constraint=models.UniqueConstraint(
                fields=("supply", "source_period_start", "source_period_end"),
                name="uniq_hh_supply_period",
            ),
        ),
        migrations.AddIndex(
            model_name="invoicecost",
            index=models.Index(
                fields=["canonical_month_key"], name="sitesync_in_canonic_1388de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicecost",
            index=models.Index(
                fields=["supply", "canonical_month_key"],
                name="sitesync_in_supply__49d2e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoicecost",
            index=models.Index(
                fields=["import_run"], name="sitesync_in_import__4028f3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicecost",
            constraint=models.UniqueConstraint(
                fields=("supply", "source_period_start", "source_period_end"),
                name="uniq_invoice_supply_period",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyconsumption",
            index=models.Index(
                fields=["canonical_month_key"], name="sitesync_mo_canonic_da822b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyconsumption",
            index=models.Index(
                fields=["supply", "canonical_month_key"],
                name="sitesync_mo_supply__f96010_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyconsumption",
            index=models.Index(
                fields=["import_run"], name="sitesync_mo_import__5ce8bd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyconsumption",
            constraint=models.UniqueConstraint(
                fields=("supply", "source_period_start", "source_period_end"),
                name="uniq_monthly_supply_period",
            ),
        ),
    ]
