# Generated by Django 5.0.1 on 2026-07-16 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesync", "0005_supply_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reporting_month", models.CharField(db_index=True, max_length=7)),
                (
                    "current_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("final", "Final")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to="sitesync.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-reporting_month", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReportVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "version_kind",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("final", "Final"),
                            ("replacement_final", "Replacement Final"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "derived_from_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_versions",
                        to="sitesync.monthlyreportversion",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="sitesync.monthlyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="current_final_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sitesync.monthlyreportversion",
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sitesync.monthlyreportversion",
            ),
        ),
        migrations.CreateModel(
            name="ReportComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visual_key", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True, default="")),
                ("is_reference_copy", models.BooleanField(default=False)),
                (
                    "source_reporting_month",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="sitesync.monthlyreportversion",
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copied_comments",
                        to="sitesync.monthlyreportversion",
                    ),
                ),
            ],
            options={
                "ordering": ["visual_key"],
            },
        ),
        migrations.AddIndex(
            model_name="monthlyreportversion",
            index=models.Index(
                fields=["report", "version_kind"], name="sitesync_mo_report__96e3c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyreportversion",
            index=models.Index(
                fields=["created_at"], name="sitesync_mo_created_5b2d9c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyreportversion",
            constraint=models.UniqueConstraint(
                fields=("report", "version_number"), name="uniq_report_version_number"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyreport",
            index=models.Index(
                fields=["site", "reporting_month"],
                name="sitesync_mo_site_id_3dc103_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyreport",
            index=models.Index(
                fields=["current_status"], name="sitesync_mo_current_08aa44_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyreport",
            constraint=models.UniqueConstraint(
                fields=("site", "reporting_month"),
                name="uniq_monthly_report_site_month",
            ),
        ),
        migrations.AddIndex(
            model_name="reportcomment",
            index=models.Index(
                fields=["report_version", "visual_key"],
                name="sitesync_re_report__795ebc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportcomment",
            index=models.Index(
                fields=["is_reference_copy"], name="sitesync_re_is_refe_a870fe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportcomment",
            constraint=models.UniqueConstraint(
                fields=("report_version", "visual_key"),
                name="uniq_comment_version_visual",
            ),
        ),
    ]
