# Generated by Django 5.0.1 on 2026-07-17 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesync', '0006_monthly_report_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('esight_meter_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('available_capacity_kva', models.DecimalField(decimal_places=3, max_digits=12)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('last_imported_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['esight_meter_code'],
            },
        ),
        migrations.CreateModel(
            name='CapacityUploadRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('accepted_rows', models.IntegerField(default=0)),
                ('rejected_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='capacityreference',
            index=models.Index(fields=['esight_meter_code'], name='sitesync_ca_esight_7a5c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityreference',
            index=models.Index(fields=['last_imported_at'], name='sitesync_ca_last_im_4f5df6_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityuploadrun',
            index=models.Index(fields=['status'], name='sitesync_ca_status_4f6c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityuploadrun',
            index=models.Index(fields=['uploaded_at'], name='sitesync_ca_upload_445ba9_idx'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='available_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Available capacity in kVA', max_digits=10, null=True),
        ),
    ]
