# Generated by Django 5.0.1 on 2026-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesync', '0007_capacity_upload_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacityreference',
            name='available_capacity_kva',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
