# Generated by Django 5.0.1 on 2026-07-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesync', '0008_capacityreference_nullable_kva'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='capacityreference',
            new_name='sitesync_ca_esight__06f6a4_idx',
            old_name='sitesync_ca_esight_7a5c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='capacityreference',
            new_name='sitesync_ca_last_im_f1a5e3_idx',
            old_name='sitesync_ca_last_im_4f5df6_idx',
        ),
        migrations.RenameIndex(
            model_name='capacityuploadrun',
            new_name='sitesync_ca_status_f3b40a_idx',
            old_name='sitesync_ca_status_4f6c9e_idx',
        ),
        migrations.RenameIndex(
            model_name='capacityuploadrun',
            new_name='sitesync_ca_uploade_55386e_idx',
            old_name='sitesync_ca_upload_445ba9_idx',
        ),
    ]
