# Generated by Django 5.0.1 on 2026-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesync', '0010_appsettings_benchmark_intensities'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='floor_area',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Site floor area from Etainabl asset data', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='floor_area_unit',
            field=models.CharField(blank=True, help_text='Original Etainabl floor area unit (sqm or sqft)', max_length=16, null=True),
        ),
    ]