# Generated by Django 5.0.1 on 2026-07-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesync", "0011_site_floor_area_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="invoice_page_limit",
            field=models.IntegerField(
                default=100, help_text="Number of invoice records to fetch per API page"
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="invoice_start_page",
            field=models.IntegerField(
                default=1, help_text="Page number invoice downloads start from"
            ),
        ),
    ]
