# Generated by Django 5.0.1 on 2026-07-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesync', '0014_team'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roleassignment',
            new_name='sitesync_ro_user_id_27665e_idx',
            old_name='sitesync_roleassignment_user_idx',
        ),
        migrations.RenameIndex(
            model_name='roleassignment',
            new_name='sitesync_ro_role_na_a3ddaf_idx',
            old_name='sitesync_roleassignment_role_name_idx',
        ),
        migrations.RenameIndex(
            model_name='roleassignment',
            new_name='sitesync_ro_user_id_a18f93_idx',
            old_name='sitesync_roleassignment_user_role_name_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='sitesync_te_name_bc178d_idx',
            old_name='sitesync_team_name_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='sitesync_te_manager_68af29_idx',
            old_name='sitesync_team_manager_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='sitesync_te_parent__0b64cb_idx',
            old_name='sitesync_team_parent_team_idx',
        ),
        migrations.RenameIndex(
            model_name='userteamassignment',
            new_name='sitesync_us_user_id_9daeb7_idx',
            old_name='sitesync_userteamassignment_user_idx',
        ),
        migrations.RenameIndex(
            model_name='userteamassignment',
            new_name='sitesync_us_team_id_44f550_idx',
            old_name='sitesync_userteamassignment_team_idx',
        ),
        migrations.RenameIndex(
            model_name='userteamassignment',
            new_name='sitesync_us_user_id_6468ba_idx',
            old_name='sitesync_userteamassignment_user_team_idx',
        ),
    ]
