# Generated by Django 5.0.1 on 2026-07-30 11:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesync", "0016_team_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "occurred_at_utc",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("actor_username_snapshot", models.CharField(max_length=150)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("action_type", models.CharField(db_index=True, max_length=64)),
                (
                    "action_outcome",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("DENIED", "Denied"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("target_entity_type", models.CharField(db_index=True, max_length=64)),
                (
                    "target_entity_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "target_entity_label",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("message", models.TextField()),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "retention_class",
                    models.CharField(default="standard", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at_utc", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor_user", "occurred_at_utc"],
                        name="sitesync_au_actor_u_f67d59_idx",
                    ),
                    models.Index(
                        fields=["action_type", "occurred_at_utc"],
                        name="sitesync_au_action__8b9ba9_idx",
                    ),
                    models.Index(
                        fields=["target_entity_type"],
                        name="sitesync_au_target__dd0505_idx",
                    ),
                ],
            },
        ),
    ]
