# Generated by Django 5.0.1 on 2026-08-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesync', '0019_site_team_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyreport',
            new_name='sitesync_mo_owner_u_97515c_idx',
            old_name='sitesync_mo_owner_u_757495_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlyreport',
            new_name='sitesync_mo_site_id_6a94b5_idx',
            old_name='sitesync_mo_site_id_0d2c7c_idx',
        ),
        migrations.RenameIndex(
            model_name='reportownershiptransferevent',
            new_name='sitesync_re_report__9ee6af_idx',
            old_name='sitesync_re_report__2f8f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='reportownershiptransferevent',
            new_name='sitesync_re_to_owne_89d347_idx',
            old_name='sitesync_re_to_owne_4240c8_idx',
        ),
        migrations.RenameIndex(
            model_name='reportownershipunavailabilityapproval',
            new_name='sitesync_re_report__bd6f7e_idx',
            old_name='sitesync_re_report__48eb45_idx',
        ),
        migrations.RenameIndex(
            model_name='reportownershipunavailabilityapproval',
            new_name='sitesync_re_approve_b36e85_idx',
            old_name='sitesync_re_approve_2da773_idx',
        ),
        migrations.RenameIndex(
            model_name='reportwritegrant',
            new_name='sitesync_re_report__de7ba8_idx',
            old_name='sitesync_re_report__12d4e5_idx',
        ),
        migrations.RenameIndex(
            model_name='reportwritegrant',
            new_name='sitesync_re_granted_72ac68_idx',
            old_name='sitesync_re_granted_85058b_idx',
        ),
    ]
