# Generated by Django 5.0.1 on 2026-08-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sitesync', '0020_rename_sitesync_mo_owner_u_757495_idx_sitesync_mo_owner_u_97515c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportwritegrant',
            name='granted_by_role',
            field=models.CharField(
                choices=[('owner', 'Owner'), ('team_lead', 'Team Lead'), ('manager', 'Manager')],
                default='owner',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='reportwritegrant',
            name='revoked_by_role',
            field=models.CharField(
                blank=True,
                choices=[('owner', 'Owner'), ('team_lead', 'Team Lead'), ('manager', 'Manager')],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='ReportWriteDelegationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke')], max_length=10)),
                ('action_by_role', models.CharField(choices=[('owner', 'Owner'), ('team_lead', 'Team Lead'), ('manager', 'Manager')], max_length=20)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('correlation_key', models.UUIDField(blank=True, null=True)),
                ('resolution_basis', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True)),
                ('action_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_delegation_events_by_actor', to=settings.AUTH_USER_MODEL)),
                ('delegate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_delegation_events', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_events', to='sitesync.monthlyreport')),
            ],
            options={
                'ordering': ['-action_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportwritedelegationevent',
            index=models.Index(fields=['report', 'action_at'], name='sitesync_re_report__4b40f3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportwritedelegationevent',
            index=models.Index(fields=['delegate_user', 'action_at'], name='sitesync_re_delegat_d12e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportwritedelegationevent',
            index=models.Index(fields=['correlation_key'], name='sitesync_re_correla_39a4ef_idx'),
        ),
    ]
