# Generated by Django 5.0.1 on 2026-08-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesync', '0021_report_write_delegation_event_and_roles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportwritedelegationevent',
            new_name='sitesync_re_report__938203_idx',
            old_name='sitesync_re_report__4b40f3_idx',
        ),
        migrations.RenameIndex(
            model_name='reportwritedelegationevent',
            new_name='sitesync_re_delegat_62244c_idx',
            old_name='sitesync_re_delegat_d12e9e_idx',
        ),
        migrations.RenameIndex(
            model_name='reportwritedelegationevent',
            new_name='sitesync_re_correla_aa063d_idx',
            old_name='sitesync_re_correla_39a4ef_idx',
        ),
    ]
