# Generated by Django 5.0.1 on 2026-08-04 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sitesync",
            "0022_rename_sitesync_re_report__4b40f3_idx_sitesync_re_report__938203_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyreport",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="validated_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_reports_validated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="validation_reopened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("awaiting_validation", "Awaiting Validation"),
                    ("validated", "Validated"),
                ],
                default="draft",
                max_length=32,
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="validator_assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="validator_assigned_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validation_assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="validator_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_monthly_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyreport",
            index=models.Index(fields=["validation_status"], name="sitesync_mo_valida_9f0c0e_idx"),
        ),
        migrations.AddIndex(
            model_name="monthlyreport",
            index=models.Index(
                fields=["validator_user", "validation_status"],
                name="sitesync_mo_valida_4f4bc7_idx",
            ),
        ),
        migrations.CreateModel(
            name="ReportValidationComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_key", models.CharField(max_length=255)),
                ("comment_text", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authored_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_report_validation_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_comments",
                        to="sitesync.monthlyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["page_key", "updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportValidationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("validator_assigned", "Validator Assigned"),
                            ("validator_reassigned", "Validator Reassigned"),
                            ("page_validated", "Page Validated"),
                            ("page_reset", "Page Reset"),
                            ("report_validated", "Report Validated"),
                            ("final_blocked", "Final Blocked"),
                            ("final_reopened", "Final Reopened"),
                        ],
                        max_length=32,
                    ),
                ),
                ("event_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "event_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_validation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_events",
                        to="sitesync.monthlyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportPageValidationState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_key", models.CharField(max_length=255)),
                ("is_validated", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reset_reason",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("reset_at", models.DateTimeField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_validation_states",
                        to="sitesync.monthlyreport",
                    ),
                ),
                (
                    "validated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_report_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["page_key"],
                "indexes": [
                    models.Index(
                        fields=["report", "is_validated"],
                        name="sitesync_re_report__fa6572_idx",
                    ),
                    models.Index(
                        fields=["report", "page_key"],
                        name="sitesync_re_report__9440ae_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reportpagevalidationstate",
            constraint=models.UniqueConstraint(
                fields=("report", "page_key"), name="uniq_report_page_validation_state"
            ),
        ),
        migrations.AddIndex(
            model_name="reportvalidationcomment",
            index=models.Index(
                fields=["report", "page_key"], name="sitesync_re_report__027ebd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportvalidationcomment",
            constraint=models.UniqueConstraint(
                fields=("report", "page_key", "authored_by_user"),
                name="uniq_report_validation_comment_author_page",
            ),
        ),
        migrations.AddIndex(
            model_name="reportvalidationevent",
            index=models.Index(
                fields=["report", "event_at"], name="sitesync_re_report__e04a1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportvalidationevent",
            index=models.Index(
                fields=["event_type", "event_at"], name="sitesync_re_event_t_a0a11a_idx"
            ),
        ),
    ]
