# Generated by Django 5.0.1 on 2026-08-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesync', '0023_report_validation_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyreport',
            new_name='sitesync_mo_validat_14a887_idx',
            old_name='sitesync_mo_valida_9f0c0e_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlyreport',
            new_name='sitesync_mo_validat_847e33_idx',
            old_name='sitesync_mo_valida_4f4bc7_idx',
        ),
    ]
